export const userFields = [
    { label: "ID", path: "id" },
    { label: "First Name", path: "firstName" },
    { label: "Last Name", path: "lastName" },
    { label: "Address Line 1", path: "address.addressLine1" },
    { label: "City", path: "address.city" },
    { label: "State", path: "address.state" },
    { label: "Zip Code", path: "address.zipCode" },
    { label: "Start Date", path: "startDate" },
    { label: "End Date", path: "endDate" },
    { label: "Active", path: "active" },
    { label: "Title", path: "title" },
    { label: "Department", path: "department" },
    { label: "Manager ID", path: "managerId" },
    { label: "Salary", path: "salary" },
    { label: "Yearly Leave Balance", path: "yearlyLeaveBalance" },
    { label: "Role", path: "role" },
    { label: "Network Username", path: "networkUsername" },
    { label: "Network Password", path: "networkPassword" },
    { label: "Photo", path: "photo" },
    { label: "Is Registered", path: "isRegistered" },
];
